workflows:
  android-workflow:
    name: Flangapp PRO Android apk
    max_build_duration: 30
    environment:
      vars:
        PACKAGE_NAME: "it.bsslab.sustechcrm"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Build APK with Flutter
        script: |
          cd . && flutter build apk --release --no-tree-shake-icons --build-name=1.0.0 --build-number=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      scripts:
        - name: HTTP notification
          script: |
            curl https://mobilebuilderapi.bss-lab.it/public/observe/notice?uid=3a0b6866-2137-6799-c38d-695bf76e0cff