workflows:
  ios-workflow:
    name: Flangapp PRO iOS with publication
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 69a6de77-1782-47e3-e053-5b8c7c11a4d1
        APP_STORE_CONNECT_KEY_IDENTIFIER: BKD935QVN7
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQ2MUxpBhgboscItX
         RA8qMLW1IZUKTIsXsj028z8/MfmgCgYIKoZIzj0DAQehRANCAASZ3cger7v53amY
         rHhXOtOst42mDyIbUpVqZDGGz/dzqAknsFHbCPosNCteGlXS8CPihKDNvWWt20Ho
         DVnvY2fc
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEowIBAAKCAQEAuetLCnmJ+/277biqf1Ii/6VwZrj5fdu+K9AnCHvTF4LKewM6
         JRGWPyMx8xyV4oU95q8Xtvjxue0V7qTz53m98TEKh5THgPRgddIO3E1ZMeNGI91B
         P7oZXwme8auEg853wse3ke88ASowTKQ8/itSSKlO+kQBluBDq+K0hAUPatpmM89j
         0pH7zlP5O9hQpXygc+J43FbEsdziWGN+A/3PDjDbe/KsHlwOeP9uEuGiWKj/M2yr
         bb4xMwnsvqTnwof16ttQfFCxCBw14VfMpUQOThRnU58k1I6TbCSVIDOIJrFDb96J
         GhPhJBuVv91ViwxV0Dpl6Q5QqzfwHj69TMXVPQIDAQABAoIBACtqfS5fxf982A0y
         NcyAOZCSCX7PfOGtdkokdG0If3nKzu5tiT89TWUGmsQ/PWg1vcgYRNUzar2Elj3R
         suxv81F25pLVRUaBquHwsQw0mtrpzEgVQ8a2NnUJWd7tMweVqEVp3p4bbBuIhtlq
         9BxVsQQrV3hdd7KMQflKemWnCdvlaEPb7rObkMPMYrsutBq5VClXyOOsG519O0Z3
         xbeE0hOuKQ9RdIA+oTd67a4OnG0eAdutJo4IFxZVHgb4kUsAluhiVjUOVqDlgXzK
         0QqOBaREIX3UMB5rhpqPGM2IcKq5TpjI2wRSKNCHE0jWNKnNaRPE33mWPkyhYtJw
         gW1yMIkCgYEAv+uhEAcH/oQGjBt4u7nVAEZHoif1iOUZMahl0CDU9/aRxcicqk8X
         LZnNKV3H7KGdgvkOJRlodLIbY7DCO5GbpPnyscM5SwktPyRLl11WeEy1JWuYtSIW
         s2OeNEoJn8fd60osuqyBDTRzXzAFsMEGcA0P0kxpHDWMkvYQB1+uVikCgYEA9/6z
         4LF8YB4tYm2b5ESf6X/vCDXDECPIZhFFu8httZu0iJr+Qh1d9BGhk/ufVBLP+Du9
         oOkOPMMaFD7XOPWOMEO53HyJmw88eNoBjSf+k+OCWOC91hAON1tvXAmvJGGelcG/
         z3y890+6e4nokmJ82RFFfshldXKXttXaak1uYPUCgYArSbx0XwGgmKrZY0DiJtIy
         U6fInXa2P+Zk2vTL8vvWShkrIUqk5130/SHXWL3FU9axOffEymxTFfEzlSTaRsdy
         eKYTDlOX5yP7f/ZE19qvG64oGJLDGENChw+h/6kYDv6xGXPpTwt0rQXwzGYcLg2D
         rI6LAo0avcFNTI7k+uHZsQKBgQCATzPaKXpkcLiimHtz212xfhO6d7Z4/0qMJJuj
         0MuSjwEVPLwYkQEvan/jBOkmoqUflilCu9I19evkVa8dNU9gAWqEfZrkszlifckX
         s32wHqIuQfl2a9AvLAut3wTTGf7nFNudCrjqbEHb8Tp3oqVd2eXO9vgnkCaW3oan
         QXC+kQKBgFS7b2lSBoCbBqznWrF4IcVgnKXrR1v2lFFnVTzZQyChLp+AJ82MfpaR
         uKJDk8KMTE0iGRTb9/UyaBQKpIWvpNJ3I0VOO0jkndjigWalBK4C8VvBqLVqz8GG
         GW+v9JhDKkAiQGw6gRkCJ83/jGZLiiE8+zgry99DINPdqA1X3Y49
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "it.bsslab.mobileagent"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --no-tree-shake-icons \
          --build-name=1.0.7 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      scripts:
        - name: HTTP notification
          script: |
            curl https://mobilebuilderapi.bss-lab.it/public/observe/notice?uid=36bc1c87-2a56-ebd0-f567-e12c19da25cf