workflows:
  ios-workflow:
    name: Flangapp PRO iOS with publication
    max_build_duration: 30
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_ISSUER_ID: 69a6de77-1782-47e3-e053-5b8c7c11a4d1
        APP_STORE_CONNECT_KEY_IDENTIFIER: BKD935QVN7
        APP_STORE_CONNECT_PRIVATE_KEY: |-
         -----BEGIN PRIVATE KEY-----
         MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQ2MUxpBhgboscItX
         RA8qMLW1IZUKTIsXsj028z8/MfmgCgYIKoZIzj0DAQehRANCAASZ3cger7v53amY
         rHhXOtOst42mDyIbUpVqZDGGz/dzqAknsFHbCPosNCteGlXS8CPihKDNvWWt20Ho
         DVnvY2fc
         -----END PRIVATE KEY-----

        CERTIFICATE_PRIVATE_KEY: |-
         -----BEGIN RSA PRIVATE KEY-----
         MIIEpAIBAAKCAQEA5R9WSaAqynkouZxDuA/qCVRexNG3SAcSrUh5TjdSOS4k7MWA
         dqLF1RDN3zsNDp6AzpVt85+Z56rNQAPOtVh2J0p4r2oynGi+8OoeAxDHBgaGEktM
         gaDDPsR1f3QDz/o1IChgSwyYHIZlrYnyPyUxWZamJ1WVfX/EFX/VfrNXxfWeBAIL
         psTqLCjeeUUxoaGbzfXJd7VSdsQ0Fl/w7oUtf6O6wQiEt/YKWfSm5qGgZgaH7GL1
         TqRB+yqWiLqjUHM/EpLk9Ahpc+W9kLjpWzN4pFDSfNhO3oYQhr0LxZcDsOhe/8rD
         l1Yd/tXYh0Xx3yUfaukvQcNcAUXbWVHwyBn76wIDAQABAoIBABOet1jeqktkTKR4
         SSQ92KCr5OGdw8AbOvIzvo+AFT5oQSk1UGbYUXCJW9e9ysRxtj36dcvi4t7/tUvC
         B7VnudZrfiInSeYy4gbnRWKl0SUm8dwnLon7Jjz9vcIIQTtSBbKXQoeqsGvg5lwR
         7/iQSsWNLPU5Uu/IPRZKOBH9cYq18DOaCcIzdpod538zMGs3BOTC44sG/EzNs3gS
         70EyEH2MLoMxBX1GvtK+o3E90TiD+nO4zMzEi/K55H2u0nLfiDmuqfD7cpsrDr3t
         axOiq3OVWoI6o4IIPpNrQCvTlclZmRAs69TuCh2Yt5M4dH6jNvqbevv23naRINz7
         WTA7LMECgYEA8hGOLoMcifxfNKByKUa+KzMdtO/gAAjrZ/Z4CX97q6MshCZfV64f
         9XSVF/GSDMOk8lRsR8kceBTaEijHZ1pyucL6x7qU4sGjDQh0lrn++JsBF7d4/cYc
         7205xpQ53grHR6VJUFrzlZH4pMUMK8M5CSYUeTDh0PAudNKKfSWYbAkCgYEA8k8L
         EPLiLk0kRoj20DpvYu4O/RZoDjJFiOVoNVdBoUNYjmYhwUdRDyvrxm61U3t2EVG/
         jJsutmixn/JRvuTxPBYrBD4hzNOTb1jRgXm2dSsH7Mkm2wJX8yIwFZx7i5rYLVne
         JIIvHvn2sanGGnMnf0lHxlSshG63FZkEHSo+jVMCgYEAmEMQoxMXdXgITqsJhAsa
         fUPW0MP9qyfxIuC2WosUuD6YNruIRzegpJ1jVr89tceuTjtqLLFEtgevr7J00v7i
         oRQS+GTVV9ii/gSuiUyPI8MkKc3fTgk6lCOpLs53o8I13UwLVH8RLqi1tLa5VCGl
         E6sfP6fOssURA6yXLebi/DkCgYBweZpkaqns3igJicgvjgBoRqK0fjMc6971Fa/S
         msc/KPixWN0wT39j8HpIKNmIf9WlYnHsvZfoWh6hZSTm3HTR9GRRWtnrrwZP+EV/
         uVSlfKz4D8M2hBb5KBRz46hBfEX+fymrfraKxXLqsyje3DcoUYa8nE9cRdw8bUPI
         mfRhOwKBgQDWru07ngsI5Qy98LO2wYpEiZQae4W8qaBctr2prQELB/BKls9SYMzh
         k+Bi/199htQBqBDtbTi2azl670wU7Emh1gCfE2Gk4Cwic5v4NXDUEdyjxsXv5JzF
         4fHBaAAKkHxsP1BZBNw8hhchW7gGOO7fQgxc/B/CAarHNdus1Nj7Dg==
         -----END RSA PRIVATE KEY-----
         

        BUNDLE_ID: "it.bsslab.mobileagent"
      flutter: 3.16.7
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create --log-api-calls --verbose
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --release --no-tree-shake-icons \
          --build-name=1.0.6 \
          --build-number=1 \
          --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      scripts:
        - name: HTTP notification
          script: |
            curl https://mobilebuilderapi.bss-lab.it/public/observe/notice?uid=ad64c6d4-2d14-8f2e-680e-a9321b0bd59e